version: "2"
services:
  redis:
    restart: always
    container_name: redis_storage
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    expose:
      - '6379'
    environment:
      - REDIS_PASSWORD=1qazse4r5t6
